version: '3'

services:
  nginx:
    image: nginx:1.22-alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/code
      - ./nginx.conf:/etc/nginx/nginx.conf

  php:
    build: .
    volumes:
      - ./:/code

  mysql:
    image: mysql:8.4
    volumes:
      - data:/var/lib/mysql

volumes:
  data: